### PR TITLE
Implement a solenoid

### PR DESCRIPTION
**Pull request by szymonlopaciuk**
## Description

Implement a thick solenoid in Xsuite.

## Checklist

Mandatory: 

- [x] I have added tests to cover my changes
- [x] All the tests are passing, including my new ones
- [x] I described my changes in this PR description

Optional:

- [x] The code I wrote follows good style practices (see [PEP 8](https://peps.python.org/pep-0008/) and [PEP 20](https://peps.python.org/pep-0020/)).
- [ ] I have updated the docs in relation to my changes, if applicable
- [ ] I have tested also GPU contexts

### CODE REVIEW

**Comment by rdemaria** [comment]
I recommend performing comparisons with small relativistic beta. A benchmark against mad-x is useful but I would not use it as a test.

You could add a test checking that a thick solenoid with zero field gives the same results of a drift for px!=py!=0.

Do you have a  write out of the equation you implemented? Do they agree with what is in paragraph 12.5.2 in https://inspirehep.net/literature/487284 ?

**Comment by szymonlopaciuk** [comment]
I can put in some tests for a small beta, I can also check if the solenoid behaves like a drift with zero field, although having it as a test is maybe not very strong, as the code explicitly catches that case and does a drift.

I have looked at the book, but in the end the code that is here (and in MAD-X) is not obviously the same as there. I could implement those equations and check for agreement there.

**Comment by rdemaria** [comment]
The check with zero fields can catch bugs. I expect the equations from the book and MAD-X (https://github.com/MethodicalAcceleratorDesign/MAD-X/pull/1129)  to implement the same solution as it is exact. Do you suspect they can be different?

**Comment by rdemaria** [comment]
For the thin solenoid, you can have a look at:

https://cds.cern.ch/record/281283/files/sl-95-012.pdf
eq. 3.37

which obtains a formulation under some approximations

**Pull request merged**
